name: OpaleModeration
version: '${project.version}'
main: fr.opaleuhc.opalemoderation.OpaleModeration
website: https://opaleuhc.fr
description: OpaleModeration plugin
authors:
  - OpaleUHC
  - Farmeurimmo
api-version: 1.19
commands:
  om:
    permission: opaleuhc.om
    aliases:
      - omb
      - opalemoderation
  ore:
    permission: opaleuhc.ore
    aliases:
      - opaleore
  cps:
    permission: opaleuhc.cps
    aliases:
      - clickpersecond